{{ config(materialized='table') }}

WITH CTE_MY_DATE AS (
  SELECT 
    TIMESTAMP_ADD(TIMESTAMP("2017-01-01 00:00:00"), INTERVAL x HOUR) AS MY_DATE
  FROM UNNEST(GENERATE_ARRAY(0, 19999)) AS x
)
SELECT
  DATE(MY_DATE) AS date,
  TIME(MY_DATE) AS time,
  MY_DATE AS datetime,
  EXTRACT(YEAR FROM MY_DATE) AS year,
  EXTRACT(MONTH FROM MY_DATE) AS month,
  FORMAT_TIMESTAMP('%B', MY_DATE) AS monthname,
  EXTRACT(DAY FROM MY_DATE) AS day,
  EXTRACT(DAYOFWEEK FROM MY_DATE) AS dayofweek,
  EXTRACT(WEEK FROM MY_DATE) AS weekofyear,
  EXTRACT(DAYOFYEAR FROM MY_DATE) AS dayofyear,
  EXTRACT(HOUR FROM MY_DATE) AS hour
FROM CTE_MY_DATE
